### ISSUE TITLE
More details about running pipline 

### ISSUE THREAD

**Issue by zhiyuanpeng** [amzn/amazon-weak-ner-needle#3]
@HMJiangGatech  Thanks for your sharing. To make sure I don't miss any steps, I list the running pipline as follows: 

1. stage1
    > **sh roberta_mlm_pretrain.sh**
2. stage2
    > **sh supervised.sh:** 
        _to train the crf model so that it has the ability to predict missing labels for weak data_
    >  **sh profile.sh:**
        _load the supervised trained crf model to predict labels for weak and dev data_
    > **sh profile2refinedweakdata.sh:**
        _assign weights for weak data_
    > **sh weak_weighted_selftrain.sh:**
        _weak supervised training_
3. stage3
    > **sh finetune.sh:**
        _use true data to fine tune bert_ 

Am I right? Thanks.

**Comment by HMJiangGatech** [comment]
Yes.
Btw, If you are starting from BERT that has been trained domain specific data (e.g., BioBERT). You can skip the Stage I, which just do the same thing.

**Comment by zhiyuanpeng** [comment]
@HMJiangGatech Thanks
