### ISSUE TITLE
No prediction results at the end of training

### ISSUE THREAD

**Issue by zhiyuanpeng** [amzn/amazon-weak-ner-needle#4]
At the end of training, it shows: 
Prediction: 100%
but there is no results printed, like p, r, f1. Only the eval results are printed.

How can I make it print the testing results? Thanks.

**Comment by HMJiangGatech** [comment]
Checkout here, it writes metrics to a file https://github.com/amzn/amazon-weak-ner-needle/blob/2885480fb4ffd066d5955d24539fc08e6b2bedda/bert-ner/run_ner.py#L290

**Comment by zhiyuanpeng** [comment]
@HMJiangGatech Thanks
