### ISSUE TITLE
File “pubmed20n0001.xml.gz”  doesn’t exists.

### ISSUE THREAD

**Issue by kk19990709** [amzn/amazon-weak-ner-needle#6]
Thanks for your sharing your work!

![image](https://user-images.githubusercontent.com/50852262/159230370-aedcbf56-3a86-475c-a792-8dcd3680f8b1.png)
When I run the bio_script/data/download_pubmed.sh, I found I can't wget the data. Can you give me some suggestions?

**Comment by kk19990709** [comment]
https://lhncbc.nlm.nih.gov/ii/information/MBR/Baselines/2020.html

**Comment by HMJiangGatech** [comment]
Wow, thanks for sharing the link of the data.
